### ISSUE TITLE
Ran the .exe and lockdown browser starts to load but then closes out

### ISSUE THREAD

**Issue by Chilly0z** [excrupro/ThreateningYeti#1]
Is there additional steps I need to be taking other then just running the .exe?

**Comment by melotic** [comment]
What version is your lockdown browser? It’s possible they released an update

**Comment by Chilly0z** [comment]
It's Version 2.0.6.01

**Comment by melotic** [comment]
I'll release an update soon!

**Comment by Chilly0z** [comment]
Right on! I'd be more then happy to donate for a working version if that
helps lmao

**Comment by melotic** [comment]
Sorry for the delay, it's now updated.
