### ISSUE TITLE
LDB Crashes on launch

### ISSUE THREAD

**Issue by KSEKK** [excrupro/ThreateningYeti#12]
I'm sorry if this is a stupid question, but how am I supposed to install MinHook as a static package with vcpkg? I've downloaded both of their master folders but I'm not sure what to do from here. A MinHook installation is necessary for ThreateningYeti to work, correct? Sorry for wasting anyone's time with this question that likely has a simple answer. 

Without a MinHook installation, when I run YetiLoader as an admin from the same folder that the browser is located in, my browser opens for a split second and then closes while my taskbar remains hidden. My taskbar only reappears when I execute the actual browser again.

Thanks for any help.

**Comment by melotic** [comment]
The installation of MinHook is only required for building from source code. What version of lockdown browser are you running?

**Comment by KSEKK** [comment]
Version 2.0.6.03

**Comment by KSEKK** [comment]
Ughh facepalm, I'm stupid as shit. Just realized it's for .02!! My mistake man, sorry for wasting your time. Would be happy to donate if you got a btc addy :)

**Comment by melotic** [comment]
No worries, I'll update soon. I should really get a script to notify me when LDB updates.

**Comment by melotic** [comment]
Updated. https://github.com/melotic/ThreateningYeti/releases/tag/2.06.03
