### ISSUE TITLE
Recommendations Running ThreateningYeti?

### ISSUE THREAD

**Issue by GuyMight44** [excrupro/ThreateningYeti#15]
Hi melotic!

First of all, thank you so much for your project and contributions! I wanted to ask you, I may need to use ThreateningYeti in the future. I am going to run it & Lockdown in a VM since I run pretty much everything I dont fully understand or control in a VM. I am sure that Lockdown may start looking for ThreateningYeti as a process and I wanted to ask, do you have any recommendations or steps to run Lockdown? For example, Running Yeti as a SYSTEM account to make sure it has full control over Lockdown? (I assume that means Lockdown would also have SYSTEM too?)

**Comment by melotic** [comment]
Lockdown has no awareness of ThreateningYeti as their is no process running when lockdown Is running (YetiLoader exits before lockdown starts), and preventative steps are taken by the injected dll to avoid detection.

Running in a VM is a safe move and probably the only precaution I see valid. There is no need for SYSTEM.
