### ISSUE TITLE
Contact

### ISSUE THREAD

**Issue by GuyMight44** [excrupro/ThreateningYeti#16]
Hi man, again, would like to thank you a lot for this project.

I was just wondering, is there any alternative way to contact you (like Discord or email) other than writing issues on your page?

Thank you

**Comment by melotic** [comment]
I could possibly create a Discord in the future, but this is a project I created for fun, and I feel like creating a discord would only involve troubleshooting people's issues. 

This is a free and open-source project and people shouldn't feel like they deserve technical support using my project. If this was a paid service (which is probably unethical), then yes, people deserve technical support.
