### ISSUE TITLE
Lockdown Browser close automatically, and task bar conceals

### ISSUE THREAD

**Issue by stupidoge** [excrupro/ThreateningYeti#17]
Sorry, i cannot run this program. I'm using the latest lcokdown browser and the latest version of YetiLoader. However, after i running this program and lockdown browser is oepned, my bottom taskbar on the computer disappears. Then, lockdown browser close automatically. How should I do?
My email is zhaok0102@gmail.com, it's a URGENT thing! I will have my task.
HLEP!!!!!!!!!!!

![image](https://user-images.githubusercontent.com/61375564/78033623-35eaeb00-7399-11ea-900d-c0eafc91ea07.png)

I would appreciate! Thanks for your helping. @melotic

ps: maybe i don't know how to use YetiLoader correctly. after the taskbar is concealed, i can take my exam on chrome? the answer is no, becasue we can only take our exam on lockdown browser, if on chrome, it will say you cannot open this exam. 
how to use your YetiLoader? My method is wrong? or there is some bugs?

**Comment by melotic** [comment]
What version of lockdown are you using?

**Comment by stupidoge** [comment]
> lockdown
the latest lockdown sir, it is same as what you posted 3 days ago.
i can run it after second try, and i find that i can use hotkey after i take the exam. HOWEVER!!!
lockdown browser warn me! it is said, if i use more than twice hotkey, my exam will be closed compulsively!!
How should i do? Run it in visual machine? or ? @melotic

**Comment by stupidoge** [comment]
@melotic 
![QQ图片20200331222631](https://user-images.githubusercontent.com/61375564/78037955-cd9f0800-739e-11ea-8159-12f4d10d6b18.jpg)
Sir, how should i do?

**Comment by stupid-doge** [comment]
Does lockdown browser detect your new-version YetiLoader?
Oh my gosh! I will cry at this exam**😱😱😭😭😭**

**Comment by dvl2014** [comment]
Please just send one message a lot of people getting spammed with at least 20 notifications from you some in past 3 hours


Sent from Yahoo Mail for iPhone


On Tuesday, March 31, 2020, 10:36 AM, stupid-doge <notifications@github.com> wrote:




Does lockdown browser detect your new-version YetiLoader?
Oh my gosh! I will cry at this exam 😱 😱 😭 😭 😭

**Comment by melotic** [comment]
Fixed this bug. Hooked the wrong WndProc. 

Download here: https://github.com/melotic/ThreateningYeti/releases/tag/2.06.03-2
