### ISSUE TITLE
Version 2.0.5.00 Support?

### ISSUE THREAD

**Issue by enderderp572** [excrupro/ThreateningYeti#19]
Our school runs LockDown version 2.0.5.00 and does not give us the option to use an updated version of the browser. Could you create a version that supports that version of LDB or does another version already support it?

**Comment by melotic** [comment]
ThreateningYeti only supports the latest version of Lockdown.

Cab you follow these steps? https://support.respondus.com/support/index.php?/Knowledgebase/Article/View/326/0/how-to-update-lockdown-browser

**Comment by enderderp572** [comment]
![86198176-A265-48B6-8F6B-423B52F0502F](https://user-images.githubusercontent.com/22330853/78269695-f0810780-74d7-11ea-874f-b6fcf28b9806.jpeg)
As I said, they do not give us the option to update past this version.

**Comment by melotic** [comment]
ThreateningYeti, unfortunately, does not support Lockdown Browser OEM. See #7
