### ISSUE TITLE
Is there anyway to hook this into Lockdown Browser when opened from Chrome?

### ISSUE THREAD

**Issue by Chilly0z** [excrupro/ThreateningYeti#2]
My D2L quiz page launches lockdown browser from Chrome so not sure how to make it launch the hooked version

**Comment by melotic** [comment]
Unforunately my school doesn't use D2L (and thus unfamiliar), but can you launch lockdown with YetiLoader and navigate to the quiz?

**Comment by dvl2014** [comment]
Unfortunately my school launches lockdown from D2L also


Sent from Yahoo Mail for iPhone


On Monday, March 9, 2020, 11:11 AM, Justin <notifications@github.com> wrote:


Unforunately my school doesn't use D2L (and thus unfamiliar), but can you launch lockdown with YetiLoader and navigate to the quiz?

**Comment by melotic** [comment]
Is it possible for you to instead start Lockdown Browser, log in to D2L from Lockdown, and take the quiz that way?

**Comment by dvl2014** [comment]
Can you make this mac compatible?

**Comment by dvl2014** [comment]
@melotic I can guaruntee you, after scanning the web only you currently have the possible respondus bypass. And colleges/universities are canceling the rest of the semesters and moving to online so you will be filled with requests to update this! I will gladly donate any amount you need if you can come up with a mac version. please let me know!

**Comment by melotic** [comment]
@dvl2014  see #4

**Comment by melotic** [comment]
This is possible, I can write another progam (YetiInterceptor?) that can intercept the opening of lockdown browser and hook it.

**Comment by dvl2014** [comment]
Ah the thing is my school doesnt make us go through respondus/lockdown, it opens up when we press on the “open lockdown to start exam” then when the separate program/window opens up it says click below to kill all applications running in background before you can continue. So can YetiInterceptir do that if opening it(quizzes and tests) from chrome —> lockdown browser? 


Sent from Yahoo Mail for iPhone


On Friday, March 13, 2020, 10:28 AM, Justin <notifications@github.com> wrote:




This is possible, I can write another progam (YetiInterceptor?) that can intercept the opening of lockdown browser and hook it.

**Comment by dvl2014** [comment]
P.S. is there alternative ways We can contact you for faster communications in regards to this possible project?


Sent from Yahoo Mail for iPhone


On Friday, March 13, 2020, 10:39 AM, David Ly <david3ly@yahoo.com> wrote:

   Ah the thing is my school doesnt make us go through respondus/lockdown, it opens up when we press on the “open lockdown to start exam” then when the separate program/window opens up it says click below to kill all applications running in background before you can continue. So can YetiInterceptir do that if opening it(quizzes and tests) from chrome —> lockdown browser? 


Sent from Yahoo Mail for iPhone


On Friday, March 13, 2020, 10:28 AM, Justin <notifications@github.com> wrote:




This is possible, I can write another progam (YetiInterceptor?) that can intercept the opening of lockdown browser and hook it.

**Comment by TheLostInPlace** [comment]
This issue could be prevented by having the application periodically scan the process list for LockDownBrowser.exe then hook into it to bypass. Basically the YetiInterceptor that you hypothesized. @melotic

**Comment by stupid-doge** [comment]
Sorry, I have installed the lastest lockdown browser, but when i run YetiLoader, i cannot run it becasue it couldn't find lockdownbrowser executable.
When i scan my lockdown browswer's file, there isn't executable lockdownbrowser's program either. 
How should i do? 
I find that when the program scan my computer, it can only open lockdownbrowser type program. I mean, there is not a file named "xxx.lockdown browser".
hope you can help me!!! Thanks so much
My email is zhaok0102@gmail.com/kevinzhao0102@qq.com
I would appreciate if you can hack this software. Wish everything is good.

**Comment by stupid-doge** [comment]
@melotic Sorry, I have installed the lastest lockdown browser, but when i run YetiLoader, i cannot run it becasue it couldn't find lockdownbrowser executable.
When i scan my lockdown browswer's file, there isn't executable lockdownbrowser's program either.
How should i do?
I find that when the program scan my computer, it can only open lockdownbrowser type program. I mean, there is not a file named "xxx.lockdown browser".
hope you can help me!!! Thanks so much
My email is zhaok0102@gmail.com/kevinzhao0102@qq.com
I would appreciate if you can hack this software. Wish everything is good.

**Comment by stupid-doge** [comment]
#11 Sorry, i cannot run this program. I'm using the latest lcokdown browser and the latest version of YetiLoader. However, after i running this program and lockdown browser is oepned, my bottom taskbar on the computer disappears. Then, lockdown browser close automatically. How should I do?
My email is zhaok0102@gmail.com, it's a URGENT thing! I will have my task.
HLEP!!!!!!!!!!!
I would appreciate! Thanks for your helping.

**Comment by ps2chiper** [comment]
I am also having this issue. I have to start Lockdown browser from the D2L page. However, when I try and start it, it will restart the currently running Lockdown browser and then quit ThreateningYeti. Maybe it would work if there was a way to navigate using Respondus, but I do not see a URL bar to input a site for navigation.

**Comment by aliveli4597** [comment]
Hi, having the same issue. Just wanted to let you guys know. I'm using firefox and when I click to link from school website firefox is asking me which program should it use to open the link, I manually added yetiloader.exe to the options besides lockdown browser; but when I try to open it with yetiloader it says that threateningyeti.dll is missing and it needs be in the same directory with yetiloader.exe, despite of both actually being in the same folder.

**Comment by Chilly0z** [comment]
@melotic Any progress on the YetiInterceptor we were discussing?

**Comment by hurrian** [comment]
@melotic There is no need to hook LockdownBrowser in memory, I believe it would be enough to pass the ``rldb:`` launch argument to the exe.

ThreateningYeti can also be assigned to take over the ``rldb:`` URI schema in Windows to launch.
![Annotation 2020-04-29 085145](https://user-images.githubusercontent.com/5042811/80552022-f0e9c100-89f7-11ea-9fd9-b3389c64313d.jpg)

**Comment by Gigi1237** [comment]
Frappola

**Comment by aliveli4597** [comment]
Is it solved with the latest commit? I've tried to login from LMS but got the same error message. And yetiloader didn't ask me whether I'm using it from LMS or not after clicking the exe.

**Comment by melotic** [comment]
@aliveli4597 Yes. Download from the build server. https://ci.appveyor.com/project/sup3rvis0r/threateningyeti/build/artifacts

**Comment by aliveli4597** [comment]
Thanks a lot!

**Comment by aliveli4597** [comment]
But I couldn't understand which URL it is, the one that I need to copy. Could you be more specific please? My LMS uses a magnet link and I couldn't see any URL.

**Comment by aliveli4597** [comment]
I finally found it, just wanted to let you know. In my system it isnt a simple command like start test but a long hash instead. So maybe you may want to change the description displaying in command prompt. Thanks again.

**Comment by abdullahsalehi** [comment]
guys i have a question n i really need help please🥺😥😥

basically after a few days i have final exam, so the exam link will be in LMS , n we have to take the password for the exam from LMS, so when i do all that  LOCKDOWN BROWSER turns on i think its from GAMALEARN company , anyways my question is " CAN I HOOK THE LOOKDOWN BROWSER AND HOW TO DO IT? " , like i want to do the exam n open up google chrome or my e-books at the same time 

can you guys help me please, i really beg you guys😭😭😭😢😢😢

**Comment by stupidoge** [comment]
That’s how yeti works...you just need run this program and alt+tab to open any chrome or ppts



from&nbsp;qq&nbsp;email


------------------ Original ------------------

**Comment by abdullahsalehi** [comment]
> That’s how yeti works...you just need run this program and alt+tab to open any chrome or ppts from&nbsp;qq&nbsp;email
> […](#)
> ------------------ Original ------------------ From: abdullahsalehi <notifications@github.com&gt; Date: Wed,May 20,2020 1:47 AM To: melotic/ThreateningYeti <ThreateningYeti@noreply.github.com&gt; Cc: stupid-doge <kevinzhao0102@qq.com&gt;, Comment <comment@noreply.github.com&gt; Subject: Re: [melotic/ThreateningYeti] Is there anyway to hook this into Lockdown Browser when opened from Chrome? (#2) guys i have a question n i really need help please🥺😥😥 basically after a few days i have final exam, so the exam link will be in LMS , n we have to take the password for the exam from LMS, so when i do all that LOCKDOWN BROWSER turns on i think its from GAMALEARN company , anyways my question is " CAN I HOOK THE LOOKDOWN BROWSER AND HOW TO DO IT? " , like i want to do the exam n open up google chrome or my e-books at the same time can you guys help me please, i really beg you guys😭😭😭😢😢😢 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

MY QUESTION WAS HOW TO DO IT ? LIKE CAN YOU GIVE ME THE STEPS TO DO IT AND THANK YOU
