### ISSUE TITLE
2.06.03 Bugfix version

### ISSUE THREAD

**Issue by Jeffery5566** [excrupro/ThreateningYeti#20]
Hi, the 2.06.03 bugfix version of Yetiloader will automatically shut down the lockdown browser when I opened it. However, if I run the 2.06.03 version(not the bugfix version), it is compatible. Maybe I am running the older Win 10? Also, is there any way or function to inspect the web code in the lockdown browser? Btw, we all very appreciate your efforts to us.

**Comment by melotic** [comment]
Closed as ThreateningYeti is updated for 2.06.05.

To inspect web traffic, you can sniff HTTP traffic with fiddler.
