### ISSUE TITLE
Win8.1 2.0.6.05 vm check

### ISSUE THREAD

**Issue by uwuforever** [excrupro/ThreateningYeti#23]
I'm using vmware + win 8.1 + LDB 2.0.6.05 + the latest release on here. Yeti gets to "Blocked call to check VM" and the browser gets to the loading screen, then it crashes with "LDB has stopped working" window. How to fix?

BTW, is there any hope for just packet scanning this? figure out the API used to get the password/whatever other crypto, figure out the correct headers to set, and not bother with an entire new VM.

**Comment by uwuforever** [comment]
Another feature i'd suggest is bypassing the certificate pinning and using system proxy settings.

**Comment by melotic** [comment]
> BTW, is there any hope for just packet scanning this? figure out the API used to get the password/whatever other crypto, figure out the correct headers to set, and not bother with an entire new VM.

They use a challenga and response cookie with MD5 sums to "verify" you're running LDB, but this is trivially bypassed. I won't release the code for a LDB emulator.

>Another feature i'd suggest is bypassing the certificate pinning and using system proxy settings.

There is no certificate pinning, you can run Fiddler or Burp and intercept and inspect the HTTP traffic all you want.

**Comment by melotic** [comment]
Updated for 2.06.05.
