### ISSUE TITLE
Not an issue but just a question!

### ISSUE THREAD

**Issue by mmysteryii** [excrupro/ThreateningYeti#24]
Sorry, I'm a newb to GitHub and came across your holy grail of a project for this damn piece of spyware. I'm curious -- does this actually work? And what are the chances of me getting actually caught by this? I'm worried that it'll track my alt+tab movements or force close me out due to suspicious behaviour. Also, I don't use a VM -- should I use that for a safety precaution or is it fine just as is? Sorry that this isnt an issue but I just dont know where to ask since this is a new project and all.

**Comment by melotic** [comment]
Yes.

This doesn't have to be a VM, but if you want to be super safe a VM could work or you know, simply getting another computer.
