### ISSUE TITLE
Will this bypass Respondus Monitor Web Cam recording?

### ISSUE THREAD

**Issue by Unorthodoxis-ui** [excrupro/ThreateningYeti#27]
Good day, I would like to thank melotic for this wonderful app, I was wondering since a previous issue addressed the data recording for mouse and keyboard input, if the code will also bypass webcam and face detection flags sent by respondus monitor during examinations.

**Comment by melotic** [comment]
No this does not bypass the webcam recording. I believe that face detection is done server-side, so it would not be bypassable.

However, it's totally possible to stream a prerecorded video or something instead of your live webcam.
