### ISSUE TITLE
Respondus flags

### ISSUE THREAD

**Issue by strikingbottle** [excrupro/ThreateningYeti#29]
Hi guys, 
I thank everyone for the beautiful job!
Have you ever used ThreateningYeti for real exams? Did it raise any flag? 
I mean in particular the flags related to the forbidden keyboard combinations (Alt-tab, task manager combination).
Thanks so much for the help!

**Comment by sxl45** [comment]
I used it multiple times in my in class mid term exams with no problem.
Note: the exams was in the class so it was without webcam and mic i think its called respondis monitor

**Comment by sxl45** [comment]
I have final exam in thursday which uses respondis monitor (Webcam and voice) and i will use it and give you feedback i dont think it will give any flags

**Comment by aliveli4597** [comment]
Thank you :)

**Comment by stupidoge** [comment]
it has no problem. we have web cams and voice record, but I successfully had a cheat.
The only weakness for this software is that it does not show task bar, and you have to use alt+tab to see slides or cheat papers.

**Comment by sxl45** [comment]
There is easier way than alt tab 
Create new desktop and put the slides or whatever you want there and in the first desktop launch the app now you can slide between desktops using Windows Key + Ctrl + Left Arrow and Windows Key + Ctrl + Right Arrow.

**Comment by stupidoge** [comment]
Sorry to bother you, bro. Does it work? 
![`G}Z5II223SFWQ4 HP($OW8](https://user-images.githubusercontent.com/61375564/82152522-624cbf00-9894-11ea-80bb-80ddb19f517e.png)

**Comment by sxl45** [comment]
Sorry for the late response but i need to thoroughly test it i actually did 3 final exams with it and it all went smooth

**Comment by sxl45** [comment]
Run it as administrator and make sure to but it in a folder and make exception in you anti virus software for that folder because for no reason it sees it as a virus

**Comment by stupidoge** [comment]
@sxl45 Would you mind to send me your version? are you Lockdown Browser 2.06.05?
My email is zhaok0102@gmail.com

**Comment by sxl45** [comment]
And also check if you have latest version of lock down and the latest version of threatening yeti

**Comment by stupidoge** [comment]
@sxl45 I succeed one month ago, but i failed just now... would you mind to send me your Yeti to my email?

**Comment by sxl45** [comment]
Ok

**Comment by sxl45** [comment]
@stupid-doge sent

**Comment by stupidoge** [comment]
I find the reason. Because my computer configuration has some problem, not the yeti problem!!!
Maybe the reason is that I move my desktop into D！！not C！！
cry...

**Comment by sxl45** [comment]
Did you try to run it as admin?

**Comment by stupidoge** [comment]
@sxl45 bro, you are a kind man. I succeed. the reason is that my desktop path is D://desktop. I change my desktop path back.
I can take the exam comfortably tomorrow!!! happy!!!

**Comment by sxl45** [comment]
No problem bro we need to help each other to pass these pointless exams

**Comment by aliveli4597** [comment]
> 
> 
> @sxl45 bro, you are a kind man. I succeed. the reason is that my desktop path is D://desktop. I change my desktop path back.
> I can take the exam comfortably tomorrow!!! happy!!!

If you have succeeded in solving it, you should also update the other issue thread you have opened.
