### ISSUE TITLE
iPad version?

### ISSUE THREAD

**Issue by joelnedev** [excrupro/ThreateningYeti#3]
Our school uses 1:1 iPads rather than laptops. Is there a way to make lockdown think self lock is on, when it isn't ? Jailbreaking isn't a problem.

**Comment by melotic** [comment]
ThreateningYeti only works on Windows with no plans to support iOS.

**Comment by dvl2014** [comment]
Youre killing me! My school just converted rest of semester to online only, we have exams at home but i need this for mac!


Sent from Yahoo Mail for iPhone


On Tuesday, March 10, 2020, 11:59 AM, Justin <notifications@github.com> wrote:


ThreateningYeti only works on Windows with no plans to support iOS.

**Comment by melotic** [comment]
Mac support isn't the same as iOS support, MacOS support is a strong possibility, but I don't have a mac. However, spring break just got extended, so there's a possibility I could write a mac version using a VM.

**Comment by joelnedev** [comment]
Ouch, takes a while to get a hackintosh working dude. Mine still isn't working with iCloud services.

Thanks,
Joel Evans

**Comment by dvl2014** [comment]
If you can do that, i would donate if interested... 


Sent from Yahoo Mail for iPhone


On Thursday, March 12, 2020, 1:36 AM, Justin <notifications@github.com> wrote:




Mac support isn't the same as iOS support, MacOS support is a strong possibility, but I don't have a mac. However, spring break just got extended, so there's a possibility I could write a mac version using a VM.
