### ISSUE TITLE
More and more Universities try to use new softwares

### ISSUE THREAD

**Issue by stupidoge** [excrupro/ThreateningYeti#31]
Maybe they find lockdown browser is easy to crack, we change another software - proctertract.
If the priciple and theory of them are same, would you mind to crack this?
link: https://www.proctortrack.com/

Thanks a lot

**Comment by aliveli4597** [comment]
It looks like proctortrack also take screenshots, which is a very serious invasion of privacy(like is that even legal?), so I doubt whether it is possible.

**Comment by melotic** [comment]
This project will only support lockdown browser.
