### ISSUE TITLE
Win7 64bit App won't start

### ISSUE THREAD

**Issue by AverageSloth** [excrupro/ThreateningYeti#32]
When I try to start the app, the window opens but then I get an error message "YetiLoader.exe has stopped working". I tried running it as an admin, but same result. With out the loader, the Browser starts without any problems
System is Win7 64bit
LockDownBrowser 2.06.05
YetiLoader is the most recent release

Since the app crashes, I can't copy the error message in the window, so I attached a screenshot
![Capture](https://user-images.githubusercontent.com/65309856/81855890-411c6380-9560-11ea-82dd-8d87045cce4b.JPG)

**Comment by melotic** [comment]
Use windows 10 💯
