### ISSUE TITLE
Two Trojans show up when Release.zip scanned with windows defender

### ISSUE THREAD

**Issue by studentbypasser** [excrupro/ThreateningYeti#35]

**Comment by aliveli4597** [comment]
Scanned with kaspersky and didnt find any threats.

**Comment by melotic** [comment]
This is flagged as a virus because it uses DLL injection, a common technique malware authors have leveraged to inject malicious code into other non-malicious programs.

**Comment by melotic** [comment]
If you are seriously concerned with malware, this is an open-source project. Read the code and compile it yourself.
