### ISSUE TITLE
Browser Lockdown OEM Issue

### ISSUE THREAD

**Issue by k4sud0n** [excrupro/ThreateningYeti#7]
When I run yetiloader, I can't select my browser lockdown **oem**.

![image](https://i.imgur.com/HWRqMsK.png)
![image](https://i.imgur.com/7886yXB.png)

I am using version 2.0.5.00.

I think #2 is the same issue as mine.

I can only open my lockdown browser with chrome.

**Comment by melotic** [comment]
Support for Lockdown Lab OEM is tricky, and this isn't the same issue as #2, as this is a different version of Lockdown Browser entirely. Manging releases for these two different versions is something that I currently don't plan on supporting right now, but possibly in the future.

Is there any way you can install the regular version of Lockdown Browser?
