### ISSUE TITLE
Filter Keylogger and Screen Recording Input

### ISSUE THREAD

**Issue by csirikak** [excrupro/ThreateningYeti#9]
According to the Respondus website [https://web.respondus.com/privacy/privacy-additional-monitor/](url), mouse, keyboard and screen activity is monitored by the LockDown Browser. Does ThreateningYeti currently filter user input such that keyboard inputs are only recorded while the browser is in view, and screen activity limited only to the browser window?

**Comment by melotic** [comment]
Yes. LDB installs hooks that monitor mouse and keyboard input, and ThreatneingYeti will disable those hooks. https://github.com/melotic/ThreateningYeti/blob/master/ThreateningYeti/hooks.cpp#L20-L51

**Comment by csirikak** [comment]
How about screen recording? Also since the hooks are disabled, do you know if the keylogger and mouse data is sent to Respondus servers?

**Comment by melotic** [comment]
Keyboard and mouse data are not sent to Respdonus servers, even if the hooks weren't disabled.
